### ISSUE TITLE
whats mean of problem_type ? 

### ISSUE THREAD

**Issue by limhasic** [Team-TUD/CTAB-GAN#23]
whats mean of problem_type ? 

Does this select which columns to consider in the final creation? Or what does it mean?

**Comment by zhao-zilong** [comment]
Hi @limhasic 

If you specify the problme_type, during the generation, it will checks the consistency between the generated features and generated label. So that later in the downstream tasks, it will enhance the performance for the synthetic data. 

You can check the ctab-gan-plus code, it supports both classification and regression: https://github.com/Team-TUD/CTAB-GAN-Plus There are two ipython notebook demos.
